// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Fixtures {
  result: Fixture[];
}

export interface Fixture {
  id:         number;
  status:     Status;
  startTime:  number;
  updateTime: number;
  homeTeam:   Details;
  awayTeam:   Details;
  country:    Details;
  tournament: Details;
  season:     Details;
  events:     Event[];
  odds:       Odd[];
  duration?:  Duration;
  homeScore?: Score;
  awayScore?: Score;
  xg?:        Xg;
}

export interface Score {
  final:     number;
  firstHalf: number;
}

export interface Details {
  id:   number;
  name: string;
}

export interface Duration {
  total:      number;
  firstHalf:  number;
  secondHalf: number;
}

export interface Event {
  homeScore:         number;
  awayScore:         number;
  minute:            number;
  author:            Details;
  teamId:            number;
  type:              EventType;
  xg:                number | null;
  additionalMinute?: number;
}

export enum EventType {
  Block = "block",
  Goal = "goal",
  Miss = "miss",
  OwnGoal = "own-goal",
  PenaltyGoal = "penalty-goal",
  PenaltyMiss = "penalty-miss",
  RedCard = "red-card",
  Save = "save",
}

export interface Odd {
  type: OddType;
  open: number;
  last: number;
}

export enum OddType {
  Away = "away",
  Draw = "draw",
  Home = "home",
  TotalOver25 = "totalOver25",
  TotalUnder25 = "totalUnder25",
}

export enum Status {
  Finished = "finished",
  Moved = "moved",
  Preview = "preview",
}

export interface Xg {
  home: number;
  away: number;
}
