version: "3"
services:
  web:
    build:
      context: "."
      dockerfile: Dockerfile
      target: base
    command: sh -c "npm install && npm run dev"
    container_name: ${COMPOSE_PROJECT_NAME}_web
    env_file:
      - ./database/.env.local
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=database
      # - DATABASE_LOGIN_URL=postgresql://next_mui_user:Y3nKA2Du&NCH@database:5432/next_mui_db
    ports:
      - 3000:3000
    volumes:
      - .:/root/app
    working_dir: /root/app
  database:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: "postgres:15"
    ports:
      - 5432:5432
    env_file:
      - ./database/.env.local
    volumes:
      - ${COMPOSE_PROJECT_NAME}_data:/var/lib/postgresql/data/
volumes:
  football_data:
