name: production-cron
on:
  schedule:
    - cron: '* 0/2 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update Production Fixtures
        run: |
          curl --request GET \
          --url 'https://kennylmq.com/api/football/initialize/fixtures' \
          --header 'Api-Secret: ${{ secrets.KENNYLMQ_PRODUCTION_API_SECRET }}'
