name: staging-cron
on:
  schedule:
    - cron: "* 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update Staging Fixtures
        run: |
          curl --request GET \
          --url 'https://staging.football.kennylmq.com/api/initialize/fixtures' \
          --header 'Api-Secret: ${{ secrets.STAGING_API_SECRET }}'
      - name: Redeploy Staging
        run: |
          curl -X POST ${{ secrets.STAGING_DEPLOY_HOOK }}
